- hosts: all
  become: true
  tasks:
    - name: Updating cache on Amazon Linux
      package:
        name:
          - "{{apache_package}}"
          - "{{php_package}}"
        state: latest
        update_cache: yes
        use: dnf
      when: ansible_distribution == "Amazon"

    - name: Updating cache on non-Amazon Linux
      package:
        name:
          - "{{apache_package}}"
          - "{{php_package}}"
        state: latest
        update_cache: yes
      when: ansible_distribution != "Amazon"

