- hosts: all
  become: true
  tasks:
    - name: Updating cache on Amazon Linux
      tags: always
      dnf:
        state: latest
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Amazon"

    - name: Updating cache on non-Amazon Linux
      tags: always
      apt:
        state: latest
        update_cache: yes
        upgrade: "dist"
      when: ansible_distribution != "Amazon"
- hosts: all
  become: true
  roles:
    - role: workstation
    - role: user
- hosts: web_server
  become: true
  roles:
    - role: webserver
- hosts: db_server
  become: true
  roles:
    - role: dbserver
